### ISSUE TITLE
SSEClient Auth Fails in Streaming

### ISSUE THREAD

**Issue by johnsonc** [childsmaidment/Pyrebase#210]
Hello,

Intermittent outages in streaming keep happening. More often than not, the same error pops up.

SSECClient seems to fail.

I've tried to monkey-patch the library as mentioned here [1], [2] but to no avail,

I was poking in the codebase to figure this out, but I'm hitting dead ends.

Anybody have insight on this?

Stack trace:
Exception in thread Thread-1:
Traceback (most recent call last):
File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
self.run()
File "/usr/lib/python3.4/threading.py", line 868, in run
self._target(*self._args, **self._kwargs)
File "/usr/local/lib/python3.4/dist-packages/Pyrebase-3.0.27-py3.4.egg/pyrebase/pyrebase.py", line 557, in start_stream
for msg in self.sse:
File "/usr/local/lib/python3.4/dist-packages/Pyrebase-3.0.27-py3.4.egg/sseclient/sseclient.py", line 85, in next
self._connect()
File "/usr/local/lib/python3.4/dist-packages/Pyrebase-3.0.27-py3.4.egg/pyrebase/pyrebase.py", line 522, in _connect
super(ClosableSSEClient, self)._connect()
File "/usr/local/lib/python3.4/dist-packages/Pyrebase-3.0.27-py3.4.egg/sseclient/sseclient.py", line 54, in _connect
self.resp.raise_for_status()
File "/usr/local/lib/python3.4/dist-packages/requests-2.11.1-py3.4.egg/requests/models.py", line 862, in raise_for_status
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://sdsea65f.firebaseio.com/test/threads.json

References:
1: thisbejim#117
2: thisbejim#143

**Comment by heston** [comment]
👍 I also just ran into this. Seems to run fine for a while, and then dies with the exact same trace.

**Comment by heston** [comment]
As I mentioned in the comments of #117, PR #249 fixes this issue.
